### ISSUE TITLE
Consider adding language about resolving conflicts

### ISSUE THREAD

**Issue by dhrubins** [EdOverflow/legal-bug-bounty#1] opened 2018-04-04 18:18 UTC
@LegalRobot, we added this after the first paragraph:
> In case of any conflict between the terms of this policy and our [Terms of Service](https://www.legalrobot.com/terms/), this policy will prevail.

We're planning to add corresponding language to our Terms, as well.

**Comment by Amitelazari** [comment] 2018-04-05 03:10
Thanks yes, this a very troubling issue in cases where bug bounty hunters are also subjected in the bug bounty policy to the product EULA that further prohibits testing, access etc, thereby creating de-facto liability. The issue is addressed in my talk and full paper. One company that deals with that nicely is paypal (as of 4/4/2018):  

"These Program Terms supplement the terms of PayPal User Agreement, the PayPal Acceptable Use Policy, and any other agreement in which you have entered with PayPal (collectively “PayPal Agreements”). The terms of those PayPal Agreements will apply to your use of, and participation in, the Bug Bounty Program as if fully set forth herein. If any inconsistency exists between the terms of the PayPal Agreements and these Program Terms, these Program Terms will control, but only with regard to the Bug Bounty Program." 

I'll push an update shortly. Thanks again - keep them coming.

This is not legal advice.

**Closed by Amitelazari** 2018-04-05 03:10 UTC
